# Stage 1: Build
FROM node:18 AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY . .

# Stage 2: Production image
FROM node:18-slim

WORKDIR /app

COPY --from=builder /app .

EXPOSE 3003
CMD ["npm", "start"]
